# Site
name: "Alejandro's Blog"
title: "Alejandro's Blog"
description: "Welcome to my blog"
meta_description: "Blog about computer science and miscellaneous."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '' 
google_analytics: 'UA-46278016-1'
disqus: false
mailchimp-list: false 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
   alejandro:
    name: Alejandro
    display_name: Alejandro
    gravatar: a1438d944315a82a4db4d0f7e652142f
    email: aege21@gmail.com
    web: https://www.alejandro.id
    description: "Currently the author of this blog (?)."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
